### ISSUE TITLE
Incompatible with webrat?

### ISSUE THREAD

**Issue by jamesbebbington** [logicaltext/rack-no-www#1]
Nice bit of middleware but I can't seem to get it to work in my integration tests. Having injected it into my rails 2.3.8 stack via:

```
ActionController::Dispatcher.middleware.insert_before(ActionController::ParamsParser, Rack::NoWWW)
```

It happily works in the browser but trying to test it in webrat 0.7.1 like so:

```
  should "be redirected to root domain when requesting application with  'www' subdomain" do
    host!("www.example.test")
    visit '/'
    assert_equal "www.example.test", host
    follow_redirect!
    assert_equal "example.test", host
    assert_equal '/', path
  end
```

I get the following error from the `visit '/'` call:

```
Rack::Lint::LintError: No Content-Type header found
```

The middleware looks pretty straight-forward so I'm not sure where the `Content-Type` header is going missing but thought I'd log this issue here in case others have come up against this.

**Comment by logicaltext** [comment]
Are you sure this error is a result of using `Rack::NoWWW`? It seems a little strange because `Rack::NoWWW` doesn't do any header manipulation--it simply forwards the `env` regardless of whether the request included the `www` subdomain.

Can you try running your integration tests without `Rack::NoWWW`? Can you also try putting the middleware further upstream in your Rack stack? I'm wondering if the `Content-Type` is being lost somewhere else during the request.

**Comment by jamesbebbington** [comment]
I agree, it is very strange, I can't see where it would be getting lost.

Removing `Rack::NoWWW` from my stack results in that test failing on the `follow_redirect!` call (as expected).

Moving `Rack::NoWWW` to the top of the stack has no effect, it still fails with the `Content-Type` header error.

Here's my stack:

```
$ rake middleware
use Rack::Lock
use ActionController::Failsafe
use HoptoadNotifier::Rack
use ActionController::Session::CookieStore, #<Proc:0x0000000101fd9f10@(eval):8>
use Rack::NoWWW
use ActionController::ParamsParser
use IdentifyMimetypesMiddleware, /^(Adobe|Shockwave) Flash/
use Rack::MethodOverride
use Rack::Head
use ActionController::StringCoercion
use Sass::Plugin::Rack
use ActiveRecord::ConnectionAdapters::ConnectionManagement
use ActiveRecord::QueryCache
run ActionController::Dispatcher.new
```

`IdentifyMimetypesMiddleware` does [play around with `Content-Type`](http://gist.github.com/595213) but it shouldn't have an effect on this test case. Removing it from the stack doesn't fix the issue.

**Comment by logicaltext** [comment]
Thanks for the follow-up. This is, indeed, most strange. I won't have time to test this myself with Rails 2.3.8 until next week, but in the meantime, here's a couple of things I would try.

First: Try a generic redirect test that uses a controller action to redirect to another URL (try the test with and without `Rack::NoWWW` in the stack). Perhaps we can see if it's a `webrat` issue with redirects.

Second: Try running the test using the 0.7.2.beta.1 version of `webrat` and see if that makes a difference.

If you have time to do these, let me know the results, and then I can conduct my own investigation at the beginning of next week.

**Comment by jamesbebbington** [comment]
Hey logicaltext,

Generic redirects work fine and I'm sorry to report that webrat 0.7.2.beta.1 doesn't fix the problem either.

Cheers.

**Comment by logicaltext** [comment]
Hmm. My initial thought is that this _is_ a `webrat` issue, given that you say all works well in the browser, right?

Can you tell me your exact setup so I can try and replicate the issue? That is, do you have a Gemfile, and any other middleware you're using? I'll try and mimic your setup, and investigate further.
